CREATE DATABASE COLLEGE;

USE COLLEGE;

CREATE TABLE DEPT (
    DEPTNO INT PRIMARY KEY,
    DNAME VARCHAR(20),
    LOC VARCHAR(20)
);

SELECT * FROM DEPT;

RENAME TABLE DEPT TO DEPARTMENT;

ALTER TABLE DEPARTMENT
ADD COLUMN PINCODE INT NOT NULL DEFAULT 0;

ALTER TABLE DEPARTMENT 
CHANGE COLUMN DNAME DEPT_NAME VARCHAR(20);

ALTER TABLE DEPARTMENT 
MODIFY LOC CHAR(20);

DROP TABLE DEPARTMENT;